"""ob1

Revision ID: 25ec027c65d9
Revises: 82ee6bd740db
Create Date: 2024-12-19 21:52:06.263127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ec027c65d9'
down_revision = '82ee6bd740db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('content_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_title', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
