"""1.1

Revision ID: be6cf92d8623
Revises: 
Create Date: 2024-12-22 15:13:41.484737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6cf92d8623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content1', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=False),
    sa.Column('content3', sa.Text(), nullable=False),
    sa.Column('content_title1', sa.Text(), nullable=False),
    sa.Column('content_title2', sa.Text(), nullable=False),
    sa.Column('content_title3', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('page')
    # ### end Alembic commands ###
